# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Service2.proto',
  package='employees',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eService2.proto\x12\temployees\"\x18\n\x08Request2\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\tResponse2\x12\x10\n\x08keywords\x18\x01 \x03(\t\"&\n\tEmployees\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x32L\n\x0eKeywordService\x12:\n\x0bGetKeywords\x12\x13.employees.Request2\x1a\x14.employees.Response2\"\x00\x62\x06proto3'
)




_REQUEST2 = _descriptor.Descriptor(
  name='Request2',
  full_name='employees.Request2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='employees.Request2.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=53,
)


_RESPONSE2 = _descriptor.Descriptor(
  name='Response2',
  full_name='employees.Response2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='employees.Response2.keywords', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=84,
)


_EMPLOYEES = _descriptor.Descriptor(
  name='Employees',
  full_name='employees.Employees',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='employees.Employees.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='employees.Employees.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Request2'] = _REQUEST2
DESCRIPTOR.message_types_by_name['Response2'] = _RESPONSE2
DESCRIPTOR.message_types_by_name['Employees'] = _EMPLOYEES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request2 = _reflection.GeneratedProtocolMessageType('Request2', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST2,
  '__module__' : 'Service2_pb2'
  # @@protoc_insertion_point(class_scope:employees.Request2)
  })
_sym_db.RegisterMessage(Request2)

Response2 = _reflection.GeneratedProtocolMessageType('Response2', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE2,
  '__module__' : 'Service2_pb2'
  # @@protoc_insertion_point(class_scope:employees.Response2)
  })
_sym_db.RegisterMessage(Response2)

Employees = _reflection.GeneratedProtocolMessageType('Employees', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEES,
  '__module__' : 'Service2_pb2'
  # @@protoc_insertion_point(class_scope:employees.Employees)
  })
_sym_db.RegisterMessage(Employees)



_KEYWORDSERVICE = _descriptor.ServiceDescriptor(
  name='KeywordService',
  full_name='employees.KeywordService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=126,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetKeywords',
    full_name='employees.KeywordService.GetKeywords',
    index=0,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYWORDSERVICE)

DESCRIPTOR.services_by_name['KeywordService'] = _KEYWORDSERVICE

# @@protoc_insertion_point(module_scope)
