# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Service2_pb2 as Service2__pb2


class KeywordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKeywords = channel.unary_unary(
                '/employees.KeywordService/GetKeywords',
                request_serializer=Service2__pb2.Request2.SerializeToString,
                response_deserializer=Service2__pb2.Response2.FromString,
                )


class KeywordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKeywords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeywordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeywords,
                    request_deserializer=Service2__pb2.Request2.FromString,
                    response_serializer=Service2__pb2.Response2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'employees.KeywordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeywordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/employees.KeywordService/GetKeywords',
            Service2__pb2.Request2.SerializeToString,
            Service2__pb2.Response2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
