// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/service2.proto

package service2

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Request2) Reset() {
	*x = Request2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request2) ProtoMessage() {}

func (x *Request2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request2.ProtoReflect.Descriptor instead.
func (*Request2) Descriptor() ([]byte, []int) {
	return file_proto_service2_proto_rawDescGZIP(), []int{0}
}

func (x *Request2) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Response2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *Response2) Reset() {
	*x = Response2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response2) ProtoMessage() {}

func (x *Response2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response2.ProtoReflect.Descriptor instead.
func (*Response2) Descriptor() ([]byte, []int) {
	return file_proto_service2_proto_rawDescGZIP(), []int{1}
}

func (x *Response2) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_proto_service2_proto protoreflect.FileDescriptor

var file_proto_service2_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x32,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x27, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x32,
	0x38, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x26, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x09, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x0a, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_service2_proto_rawDescOnce sync.Once
	file_proto_service2_proto_rawDescData = file_proto_service2_proto_rawDesc
)

func file_proto_service2_proto_rawDescGZIP() []byte {
	file_proto_service2_proto_rawDescOnce.Do(func() {
		file_proto_service2_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service2_proto_rawDescData)
	})
	return file_proto_service2_proto_rawDescData
}

var file_proto_service2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_service2_proto_goTypes = []interface{}{
	(*Request2)(nil),  // 0: Request2
	(*Response2)(nil), // 1: Response2
}
var file_proto_service2_proto_depIdxs = []int32{
	0, // 0: KeywordService.GetKeywords:input_type -> Request2
	1, // 1: KeywordService.GetKeywords:output_type -> Response2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service2_proto_init() }
func file_proto_service2_proto_init() {
	if File_proto_service2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_service2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service2_proto_goTypes,
		DependencyIndexes: file_proto_service2_proto_depIdxs,
		MessageInfos:      file_proto_service2_proto_msgTypes,
	}.Build()
	File_proto_service2_proto = out.File
	file_proto_service2_proto_rawDesc = nil
	file_proto_service2_proto_goTypes = nil
	file_proto_service2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KeywordServiceClient is the client API for KeywordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeywordServiceClient interface {
	GetKeywords(ctx context.Context, in *Request2, opts ...grpc.CallOption) (*Response2, error)
}

type keywordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeywordServiceClient(cc grpc.ClientConnInterface) KeywordServiceClient {
	return &keywordServiceClient{cc}
}

func (c *keywordServiceClient) GetKeywords(ctx context.Context, in *Request2, opts ...grpc.CallOption) (*Response2, error) {
	out := new(Response2)
	err := c.cc.Invoke(ctx, "/KeywordService/GetKeywords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeywordServiceServer is the server API for KeywordService service.
type KeywordServiceServer interface {
	GetKeywords(context.Context, *Request2) (*Response2, error)
}

// UnimplementedKeywordServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKeywordServiceServer struct {
}

func (*UnimplementedKeywordServiceServer) GetKeywords(context.Context, *Request2) (*Response2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeywords not implemented")
}

func RegisterKeywordServiceServer(s *grpc.Server, srv KeywordServiceServer) {
	s.RegisterService(&_KeywordService_serviceDesc, srv)
}

func _KeywordService_GetKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordServiceServer).GetKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KeywordService/GetKeywords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordServiceServer).GetKeywords(ctx, req.(*Request2))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeywordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "KeywordService",
	HandlerType: (*KeywordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKeywords",
			Handler:    _KeywordService_GetKeywords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service2.proto",
}
